# Generated by Django 2.0.1 on 2019-08-24 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_auto_20190824_2304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='score1',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='score2',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='score3',
        ),
        migrations.AddField(
            model_name='questions',
            name='score_cntr',
            field=models.IntegerField(default=0),
        ),
    ]
