# Generated by Django 2.0.1 on 2019-08-25 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_auto_20190825_0129'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_cntr', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='questions',
            name='score_cntr',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='temp1_Ans',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='temp2_Ans',
        ),
        migrations.AddField(
            model_name='profile',
            name='temp1_Ans',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='temp2_Ans',
            field=models.CharField(default='', max_length=100),
        ),
    ]
