# Generated by Django 2.2.3 on 2019-08-29 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0017_profile_visited'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='buff1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='buff2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='buff3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='buff_cntr',
            field=models.IntegerField(default=1),
        ),
    ]
