# Generated by Django 2.2.3 on 2019-09-08 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0033_profile_timer'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='correct',
            field=models.IntegerField(default=0),
        ),
    ]
