# Generated by Django 2.2.3 on 2019-09-09 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0034_profile_correct'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='life_counter',
            new_name='endian_counter',
        ),
    ]
