# Generated by Django 2.2.3 on 2019-09-09 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0037_auto_20190909_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='curqno',
            field=models.IntegerField(default=0),
        ),
    ]
