# Generated by Django 2.2.3 on 2019-09-10 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0039_profile_after_bonus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='lifeline1',
            field=models.IntegerField(default=1),
        ),
    ]
