# Generated by Django 2.2.3 on 2019-09-10 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0040_auto_20190910_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='lifeline1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='stack',
            field=models.IntegerField(default=4),
        ),
    ]
