# Generated by Django 2.2.3 on 2019-09-18 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0043_auto_20190918_0011'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='after_buff',
            field=models.IntegerField(default=0),
        ),
    ]
