# Generated by Django 2.2.3 on 2019-09-20 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0044_profile_after_buff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='score',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='questions',
            name='question',
            field=models.CharField(default='', max_length=5000),
        ),
    ]
