# Generated by Django 2.0.1 on 2019-08-15 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='option1',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='option2',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='option3',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='option4',
        ),
        migrations.AddField(
            model_name='questions',
            name='attempt1',
            field=models.TextField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='questions',
            name='attempt2',
            field=models.TextField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='questions',
            name='answer',
            field=models.TextField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='questions',
            name='question',
            field=models.TextField(default='', max_length=500),
        ),
    ]
