# Generated by Django 2.0.1 on 2019-08-15 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_auto_20190815_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='answer',
            field=models.TextField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='questions',
            name='attempt1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='questions',
            name='attempt2',
            field=models.TextField(blank=True, null=True),
        ),
    ]
