# Generated by Django 2.0.1 on 2019-08-25 06:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_auto_20190815_1744'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_cntr', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='login_time',
            field=models.DateTimeField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='logout_time',
            field=models.DateTimeField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='temp1_Ans',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='temp2_Ans',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mob2',
            field=models.CharField(default='9999999999', max_length=12),
        ),
        migrations.AlterField(
            model_name='profile',
            name='p2_email',
            field=models.CharField(default='a@a.com', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='p2_name',
            field=models.CharField(default='a', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='questions',
            name='answer',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='questions',
            name='attempt1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='questions',
            name='attempt2',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
