# Generated by Django 2.2.3 on 2019-08-28 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_auto_20190825_1146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='temp1_Ans',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='temp2_Ans',
        ),
        migrations.AddField(
            model_name='profile',
            name='curqno',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='decr',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='profile',
            name='incr',
            field=models.IntegerField(default=4),
        ),
    ]
