# Generated by Django 2.2.3 on 2019-08-29 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_auto_20190829_0055'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Score',
        ),
    ]
