# Generated by Django 2.0.1 on 2019-08-30 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_auto_20190829_2015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='resp',
        ),
        migrations.AddField(
            model_name='response',
            name='attempt1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='response',
            name='attepmt2',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mob1',
            field=models.CharField(max_length=10),
        ),
    ]
