# Generated by Django 2.0.1 on 2019-08-30 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0013_auto_20190830_0640'),
    ]

    operations = [
        migrations.RenameField(
            model_name='response',
            old_name='attepmt2',
            new_name='attempt2',
        ),
    ]
