# Generated by Django 2.0.1 on 2019-08-31 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0014_auto_20190830_0711'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='attempt_cntr',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='response',
            name='attempt1',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='response',
            name='attempt2',
            field=models.IntegerField(default=-1),
        ),
    ]
