# Generated by Django 2.2.3 on 2019-09-01 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0016_auto_20190901_1219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='username',
        ),
        migrations.AlterField(
            model_name='response',
            name='attempt1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='response',
            name='attempt2',
            field=models.IntegerField(default=0),
        ),
    ]
