# Generated by Django 2.0.1 on 2019-09-01 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0018_profile_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='level',
            field=models.IntegerField(default=2),
        ),
    ]
