# Generated by Django 2.0.1 on 2019-09-01 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0019_questions_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='visited',
            field=models.CharField(default='', max_length=100),
        ),
    ]
