# Generated by Django 2.0.1 on 2019-09-12 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0022_auto_20190909_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='curqno',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='profile',
            name='score',
            field=models.IntegerField(default=1),
        ),
    ]
