# Generated by Django 2.0.1 on 2019-09-17 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0023_auto_20190912_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='att1',
            field=models.IntegerField(default=0),
        ),
    ]
