# Generated by Django 2.2.3 on 2019-08-06 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='answer',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='questions',
            name='option1',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='questions',
            name='option2',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='questions',
            name='option3',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='questions',
            name='option4',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='questions',
            name='question',
            field=models.CharField(default='', max_length=500),
        ),
    ]
