# Generated by Django 2.0.1 on 2019-08-14 17:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0002_auto_20190806_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p1_name', models.CharField(max_length=100)),
                ('p2_name', models.CharField(max_length=100)),
                ('p1_email', models.CharField(max_length=100)),
                ('p2_email', models.CharField(max_length=100)),
                ('mob1', models.CharField(max_length=12)),
                ('mob2', models.CharField(max_length=12)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
