# Generated by Django 2.0.1 on 2019-08-20 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='login_logout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_time', models.DateTimeField(default='', max_length=100)),
                ('logout_time', models.DateTimeField(default='', max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='mob2',
            field=models.CharField(default='9999999999', max_length=12),
        ),
        migrations.AlterField(
            model_name='profile',
            name='p2_email',
            field=models.CharField(default='a@a.com', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='p2_name',
            field=models.CharField(default='a', max_length=100),
        ),
    ]
