# Generated by Django 2.0.1 on 2019-08-20 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_auto_20190821_0018'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='login_logout',
            new_name='LILO',
        ),
    ]
