# Generated by Django 2.0.1 on 2019-08-25 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_auto_20190825_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='year',
            field=models.CharField(choices=[('FE', 'Freshman'), ('SE', 'Senior')], default='FE', max_length=2),
        ),
        migrations.AddField(
            model_name='questions',
            name='level',
            field=models.CharField(default='', max_length=2),
        ),
    ]
