# Generated by Django 2.2.3 on 2019-08-27 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0013_response'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Score',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='temp1_Ans',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='temp2_Ans',
        ),
        migrations.AddField(
            model_name='profile',
            name='decr',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='profile',
            name='incr',
            field=models.IntegerField(default=4),
        ),
    ]
