# Generated by Django 2.2.3 on 2019-08-28 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0015_profile_visited'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='visited',
        ),
    ]
