# Generated by Django 2.2.3 on 2019-09-01 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0023_auto_20190901_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='list_cntr',
            field=models.IntegerField(default=0),
        ),
    ]
