# Generated by Django 2.2.3 on 2019-09-01 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0024_profile_list_cntr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='visited',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
