# Generated by Django 2.0.1 on 2019-09-02 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0026_auto_20190901_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='life_counter',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='profile',
            name='lifeline1',
            field=models.IntegerField(default=0),
        ),
    ]
