# Generated by Django 2.2.3 on 2019-09-05 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0027_auto_20190902_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='buff_que_added',
            field=models.IntegerField(default=0),
        ),
    ]
