# Generated by Django 2.2.3 on 2019-09-05 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0028_profile_buff_que_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='remain_time',
            field=models.DateTimeField(max_length=100, null=True),
        ),
    ]
