# Generated by Django 2.2.3 on 2019-09-05 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0029_profile_remain_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='remain_time',
            field=models.TimeField(max_length=100, null=True),
        ),
    ]
