# Generated by Django 2.2.3 on 2019-09-06 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0032_auto_20190906_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='timer',
            field=models.TimeField(null=True),
        ),
    ]
