# Generated by Django 2.2.3 on 2019-09-09 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0036_profile_life_counter'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bon_intime',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='bon_outtime',
            field=models.TimeField(null=True),
        ),
    ]
