# Generated by Django 2.2.3 on 2019-09-17 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0042_auto_20190912_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='stack',
            field=models.IntegerField(default=6),
        ),
        migrations.AlterField(
            model_name='questions',
            name='level',
            field=models.IntegerField(default=0),
        ),
    ]
