# Generated by Django 2.2.3 on 2019-09-20 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0046_auto_20190920_0754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='score',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='questions',
            name='question',
            field=models.TextField(default='', max_length=5000),
        ),
    ]
