# Generated by Django 2.2.3 on 2019-09-20 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0047_auto_20190920_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bon_ans',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='profile',
            name='bon_flag',
            field=models.IntegerField(default=0),
        ),
    ]
